// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v3.19.1
// source: counter.proto

/* eslint-disable */
import { type CallContext, type CallOptions } from "nice-grpc-common";
import _m0 from "protobufjs/minimal.js";
import { Empty } from "./google/protobuf/empty.js";

export const protobufPackage = "counter";

export interface CounterIncreaseRequest {
  delta: number;
}

export interface CounterState {
  counter: number;
}

function createBaseCounterIncreaseRequest(): CounterIncreaseRequest {
  return { delta: 0 };
}

export const CounterIncreaseRequest = {
  encode(message: CounterIncreaseRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.delta !== 0) {
      writer.uint32(8).int32(message.delta);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CounterIncreaseRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCounterIncreaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.delta = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CounterIncreaseRequest {
    return { delta: isSet(object.delta) ? globalThis.Number(object.delta) : 0 };
  },

  toJSON(message: CounterIncreaseRequest): unknown {
    const obj: any = {};
    if (message.delta !== 0) {
      obj.delta = Math.round(message.delta);
    }
    return obj;
  },

  create(base?: DeepPartial<CounterIncreaseRequest>): CounterIncreaseRequest {
    return CounterIncreaseRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CounterIncreaseRequest>): CounterIncreaseRequest {
    const message = createBaseCounterIncreaseRequest();
    message.delta = object.delta ?? 0;
    return message;
  },
};

function createBaseCounterState(): CounterState {
  return { counter: 0 };
}

export const CounterState = {
  encode(message: CounterState, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.counter !== 0) {
      writer.uint32(8).int32(message.counter);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CounterState {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCounterState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.counter = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CounterState {
    return { counter: isSet(object.counter) ? globalThis.Number(object.counter) : 0 };
  },

  toJSON(message: CounterState): unknown {
    const obj: any = {};
    if (message.counter !== 0) {
      obj.counter = Math.round(message.counter);
    }
    return obj;
  },

  create(base?: DeepPartial<CounterState>): CounterState {
    return CounterState.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CounterState>): CounterState {
    const message = createBaseCounterState();
    message.counter = object.counter ?? 0;
    return message;
  },
};

export type SingleCounterDefinition = typeof SingleCounterDefinition;
export const SingleCounterDefinition = {
  name: "SingleCounter",
  fullName: "counter.SingleCounter",
  methods: {
    increase: {
      name: "increase",
      requestType: CounterIncreaseRequest,
      requestStream: false,
      responseType: CounterState,
      responseStream: false,
      options: {},
    },
    current: {
      name: "current",
      requestType: Empty,
      requestStream: false,
      responseType: CounterState,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface SingleCounterServiceImplementation<CallContextExt = {}> {
  increase(request: CounterIncreaseRequest, context: CallContext & CallContextExt): Promise<DeepPartial<CounterState>>;
  current(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<CounterState>>;
}

export interface SingleCounterClient<CallOptionsExt = {}> {
  increase(request: DeepPartial<CounterIncreaseRequest>, options?: CallOptions & CallOptionsExt): Promise<CounterState>;
  current(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<CounterState>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
