// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Range {
    #[prost(uint32, tag = "1")]
    pub start: u32,
    #[prost(uint32, optional, tag = "2")]
    pub end: ::core::option::Option<u32>,
}
